// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqjsihdahpwqwtlugtml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxanNpaGRhaHB3cXd0bHVndG1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NTgzODcsImV4cCI6MjA2NDMzNDM4N30.cTHKvPW7feX340BtGfCNMvqcxWC6OPOzbBiLFqaTUBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);